
---
events:
  -
    kind: "message-v1"
    backtrace:
      - "/snap/cmake/1425/share/cmake-3.31/Modules/CMakeDetermineSystem.cmake:205 (message)"
      - "CMakeLists.txt:3 (project)"
    message: |
      The system is: Linux - 6.8.0-48-generic - x86_64
  -
    kind: "message-v1"
    backtrace:
      - "/snap/cmake/1425/share/cmake-3.31/Modules/CMakeDetermineCompilerId.cmake:17 (message)"
      - "/snap/cmake/1425/share/cmake-3.31/Modules/CMakeDetermineCompilerId.cmake:64 (__determine_compiler_id_test)"
      - "/snap/cmake/1425/share/cmake-3.31/Modules/CMakeDetermineFortranCompiler.cmake:190 (CMAKE_DETERMINE_COMPILER_ID)"
      - "CMakeLists.txt:3 (project)"
    message: |
      Compiling the Fortran compiler identification source file "CMakeFortranCompilerId.F" failed.
      Compiler: CMAKE_Fortran_COMPILER-NOTFOUND 
      Build flags: 
      Id flags: -v 
      
      The output was:
      no such file or directory
      
      
  -
    kind: "message-v1"
    backtrace:
      - "/snap/cmake/1425/share/cmake-3.31/Modules/CMakeDetermineCompilerId.cmake:17 (message)"
      - "/snap/cmake/1425/share/cmake-3.31/Modules/CMakeDetermineCompilerId.cmake:64 (__determine_compiler_id_test)"
      - "/snap/cmake/1425/share/cmake-3.31/Modules/CMakeDetermineFortranCompiler.cmake:190 (CMAKE_DETERMINE_COMPILER_ID)"
      - "CMakeLists.txt:3 (project)"
    message: |
      Compiling the Fortran compiler identification source file "CMakeFortranCompilerId.F" failed.
      Compiler: CMAKE_Fortran_COMPILER-NOTFOUND 
      Build flags: 
      Id flags: -v;-c 
      
      The output was:
      no such file or directory
      
      
  -
    kind: "message-v1"
    backtrace:
      - "/snap/cmake/1425/share/cmake-3.31/Modules/CMakeDetermineCompilerId.cmake:17 (message)"
      - "/snap/cmake/1425/share/cmake-3.31/Modules/CMakeDetermineCompilerId.cmake:64 (__determine_compiler_id_test)"
      - "/snap/cmake/1425/share/cmake-3.31/Modules/CMakeDetermineFortranCompiler.cmake:190 (CMAKE_DETERMINE_COMPILER_ID)"
      - "CMakeLists.txt:3 (project)"
    message: |
      Compiling the Fortran compiler identification source file "CMakeFortranCompilerId.F" failed.
      Compiler: CMAKE_Fortran_COMPILER-NOTFOUND 
      Build flags: 
      Id flags:  
      
      The output was:
      no such file or directory
      
      
  -
    kind: "message-v1"
    backtrace:
      - "/snap/cmake/1425/share/cmake-3.31/Modules/CMakeDetermineCompilerId.cmake:17 (message)"
      - "/snap/cmake/1425/share/cmake-3.31/Modules/CMakeDetermineCompilerId.cmake:64 (__determine_compiler_id_test)"
      - "/snap/cmake/1425/share/cmake-3.31/Modules/CMakeDetermineFortranCompiler.cmake:190 (CMAKE_DETERMINE_COMPILER_ID)"
      - "CMakeLists.txt:3 (project)"
    message: |
      Compiling the Fortran compiler identification source file "CMakeFortranCompilerId.F" failed.
      Compiler: CMAKE_Fortran_COMPILER-NOTFOUND 
      Build flags: 
      Id flags: -c 
      
      The output was:
      no such file or directory
      
      
  -
    kind: "message-v1"
    backtrace:
      - "/snap/cmake/1425/share/cmake-3.31/Modules/CMakeDetermineCompilerId.cmake:17 (message)"
      - "/snap/cmake/1425/share/cmake-3.31/Modules/CMakeDetermineCompilerId.cmake:64 (__determine_compiler_id_test)"
      - "/snap/cmake/1425/share/cmake-3.31/Modules/CMakeDetermineFortranCompiler.cmake:190 (CMAKE_DETERMINE_COMPILER_ID)"
      - "CMakeLists.txt:3 (project)"
    message: |
      Compiling the Fortran compiler identification source file "CMakeFortranCompilerId.F" failed.
      Compiler: CMAKE_Fortran_COMPILER-NOTFOUND 
      Build flags: 
      Id flags: -fpp 
      
      The output was:
      no such file or directory
      
      
  -
    kind: "message-v1"
    backtrace:
      - "/snap/cmake/1425/share/cmake-3.31/Modules/CMakeDetermineCompilerId.cmake:17 (message)"
      - "/snap/cmake/1425/share/cmake-3.31/Modules/CMakeDetermineCompilerId.cmake:64 (__determine_compiler_id_test)"
      - "/snap/cmake/1425/share/cmake-3.31/Modules/CMakeDetermineFortranCompiler.cmake:190 (CMAKE_DETERMINE_COMPILER_ID)"
      - "CMakeLists.txt:3 (project)"
    message: |
      Compiling the Fortran compiler identification source file "CMakeFortranCompilerId.F" failed.
      Compiler: CMAKE_Fortran_COMPILER-NOTFOUND 
      Build flags: 
      Id flags: --cpp-infer 
      
      The output was:
      no such file or directory
      
      
  -
    kind: "message-v1"
    backtrace:
      - "/snap/cmake/1425/share/cmake-3.31/Modules/CMakeDetermineCompilerId.cmake:17 (message)"
      - "/snap/cmake/1425/share/cmake-3.31/Modules/CMakeDetermineCompilerId.cmake:64 (__determine_compiler_id_test)"
      - "/snap/cmake/1425/share/cmake-3.31/Modules/CMakeDetermineFortranCompiler.cmake:190 (CMAKE_DETERMINE_COMPILER_ID)"
      - "CMakeLists.txt:3 (project)"
    message: |
      Compiling the Fortran compiler identification source file "CMakeFortranCompilerId.F" failed.
      Compiler: CMAKE_Fortran_COMPILER-NOTFOUND 
      Build flags: 
      Id flags: -v 
      
      The output was:
      no such file or directory
      
      
  -
    kind: "message-v1"
    backtrace:
      - "/snap/cmake/1425/share/cmake-3.31/Modules/CMakeDetermineCompilerId.cmake:17 (message)"
      - "/snap/cmake/1425/share/cmake-3.31/Modules/CMakeDetermineCompilerId.cmake:64 (__determine_compiler_id_test)"
      - "/snap/cmake/1425/share/cmake-3.31/Modules/CMakeDetermineFortranCompiler.cmake:190 (CMAKE_DETERMINE_COMPILER_ID)"
      - "CMakeLists.txt:3 (project)"
    message: |
      Compiling the Fortran compiler identification source file "CMakeFortranCompilerId.F" failed.
      Compiler: CMAKE_Fortran_COMPILER-NOTFOUND 
      Build flags: 
      Id flags: -v;-c 
      
      The output was:
      no such file or directory
      
      
  -
    kind: "message-v1"
    backtrace:
      - "/snap/cmake/1425/share/cmake-3.31/Modules/CMakeDetermineCompilerId.cmake:17 (message)"
      - "/snap/cmake/1425/share/cmake-3.31/Modules/CMakeDetermineCompilerId.cmake:64 (__determine_compiler_id_test)"
      - "/snap/cmake/1425/share/cmake-3.31/Modules/CMakeDetermineFortranCompiler.cmake:190 (CMAKE_DETERMINE_COMPILER_ID)"
      - "CMakeLists.txt:3 (project)"
    message: |
      Compiling the Fortran compiler identification source file "CMakeFortranCompilerId.F" failed.
      Compiler: CMAKE_Fortran_COMPILER-NOTFOUND 
      Build flags: 
      Id flags:  
      
      The output was:
      no such file or directory
      
      
  -
    kind: "message-v1"
    backtrace:
      - "/snap/cmake/1425/share/cmake-3.31/Modules/CMakeDetermineCompilerId.cmake:17 (message)"
      - "/snap/cmake/1425/share/cmake-3.31/Modules/CMakeDetermineCompilerId.cmake:64 (__determine_compiler_id_test)"
      - "/snap/cmake/1425/share/cmake-3.31/Modules/CMakeDetermineFortranCompiler.cmake:190 (CMAKE_DETERMINE_COMPILER_ID)"
      - "CMakeLists.txt:3 (project)"
    message: |
      Compiling the Fortran compiler identification source file "CMakeFortranCompilerId.F" failed.
      Compiler: CMAKE_Fortran_COMPILER-NOTFOUND 
      Build flags: 
      Id flags: -c 
      
      The output was:
      no such file or directory
      
      
  -
    kind: "message-v1"
    backtrace:
      - "/snap/cmake/1425/share/cmake-3.31/Modules/CMakeDetermineCompilerId.cmake:17 (message)"
      - "/snap/cmake/1425/share/cmake-3.31/Modules/CMakeDetermineCompilerId.cmake:64 (__determine_compiler_id_test)"
      - "/snap/cmake/1425/share/cmake-3.31/Modules/CMakeDetermineFortranCompiler.cmake:190 (CMAKE_DETERMINE_COMPILER_ID)"
      - "CMakeLists.txt:3 (project)"
    message: |
      Compiling the Fortran compiler identification source file "CMakeFortranCompilerId.F" failed.
      Compiler: CMAKE_Fortran_COMPILER-NOTFOUND 
      Build flags: 
      Id flags: -fpp 
      
      The output was:
      no such file or directory
      
      
  -
    kind: "message-v1"
    backtrace:
      - "/snap/cmake/1425/share/cmake-3.31/Modules/CMakeDetermineCompilerId.cmake:17 (message)"
      - "/snap/cmake/1425/share/cmake-3.31/Modules/CMakeDetermineCompilerId.cmake:64 (__determine_compiler_id_test)"
      - "/snap/cmake/1425/share/cmake-3.31/Modules/CMakeDetermineFortranCompiler.cmake:190 (CMAKE_DETERMINE_COMPILER_ID)"
      - "CMakeLists.txt:3 (project)"
    message: |
      Compiling the Fortran compiler identification source file "CMakeFortranCompilerId.F" failed.
      Compiler: CMAKE_Fortran_COMPILER-NOTFOUND 
      Build flags: 
      Id flags: --cpp-infer 
      
      The output was:
      no such file or directory
      
      
...
